### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by chrissRo** [Sydrimon/memeversation#3]
Pls rewrite in x86 assembly for better performance 
Thanks Sir

**Comment by Reitermaniac** [comment]
This issue is already solved.
Check out the following link https://youtu.be/dQw4w9WgXcQ

**Comment by chrissRo** [comment]
@Reitermaniac 
Tahnk you Sir
I checked out your link but It Is not working on my machine
Have Raspberry Pi 2, It Is not working, and help highly appreciate 
Thank you Sir

**Comment by Reitermaniac** [comment]
@chrissRo ah my bad 
I thought you whould use newer Hardware.
I'd recomend using the Raspberry Pi 3B+ or try using the following https://youtu.be/dQw4w9WgXcQ

**Comment by chrissRo** [comment]
@Reitermaniac 
Hello Sir
Raspberry pi3 Is not x87 machine so please Stick to topic thanks Sir 
@Sydrimon pls give assembly code for better performance

**Comment by Reitermaniac** [comment]
@chrissRo 
My bad 
I'd recomend the good ol Latte Panda 
An awesome alternative to the Raspberry Pi

**Comment by chrissRo** [comment]
@Sydrimon pls give Code Tank you

**Comment by Reitermaniac** [comment]
Did you already try the Late Panda? 

Pls give me an answer 
How did it work

**Comment by chrissRo** [comment]
No Sir 
Will do as soon as @Sydrimon provides assembly code for x86 architecture 
Thanks Sir, this helped me a lot

**Comment by Reitermaniac** [comment]
@chrissRo 
Please mark my post as solution
Thank you

**Comment by Sydrimon** [comment]
> Pls rewrite in x86 assembly for better performance
> Thanks Sir

Hello @chrissRo,
please provide detailed benchmarks and show the critical code sections.
As soon as you can provide more info I'll look into this subject.

Kind regards,
Sydrimon
